apiVersion: v1
kind: Pod
metadata:
  name: network-controller
spec:
  containers:
    - name: network-controller
      image: network-controller:latest
      imagePullPolicy: IfNotPresent
  serviceAccountName: network-service-account